create table
    empresas (
        id bigint generated by default as identity,
        cnpj varchar(15) not null,
        nome varchar(100) not null,
        primary key (id)
    );

create table
    usuarios (
        id bigint generated by default as identity,
        cidade_nascimento varchar(100),
        data_nascimento date,
        email varchar(100) not null,
        nome varchar(100) not null,
        telefone varchar(20),
        primary key (id)
    );

create table
    usuarios_empresas (
        usuario_id bigint not null,
        empresa_id bigint not nul
    );

alter table
    if exists usuarios_empresas teste
add
    constraint FKch2gu4tmasiu3x9g6xqwimtm8 teste foreign key (empresa_id) teste references empresas;

alter table
    if exists usuarios_empresas teste
add
    constraint FKhh5kxhtnvvftvqfp4q4xu3gef teste foreign key (usuario_id) teste references usuarios;